//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS_lab_10_Web.MSUWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MSUWS.MSUWSSoap")]
    public interface MSUWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        int Sub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        int Mul(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSessionValue", ReplyAction="*")]
        int GetSessionValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetSessionValue", ReplyAction="*")]
        void SetSessionValue(int value);
        
        // CODEGEN: Контракт генерации сообщений с именем GetHistoryResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHistory", ReplyAction="*")]
        PIS_lab_10_Web.MSUWS.GetHistoryResponse GetHistory(PIS_lab_10_Web.MSUWS.GetHistoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHistory", Namespace="http://tempuri.org/", Order=0)]
        public PIS_lab_10_Web.MSUWS.GetHistoryRequestBody Body;
        
        public GetHistoryRequest() {
        }
        
        public GetHistoryRequest(PIS_lab_10_Web.MSUWS.GetHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetHistoryRequestBody {
        
        public GetHistoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public PIS_lab_10_Web.MSUWS.GetHistoryResponseBody Body;
        
        public GetHistoryResponse() {
        }
        
        public GetHistoryResponse(PIS_lab_10_Web.MSUWS.GetHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHistoryResult;
        
        public GetHistoryResponseBody() {
        }
        
        public GetHistoryResponseBody(string GetHistoryResult) {
            this.GetHistoryResult = GetHistoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MSUWSSoapChannel : PIS_lab_10_Web.MSUWS.MSUWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MSUWSSoapClient : System.ServiceModel.ClientBase<PIS_lab_10_Web.MSUWS.MSUWSSoap>, PIS_lab_10_Web.MSUWS.MSUWSSoap {
        
        public MSUWSSoapClient() {
        }
        
        public MSUWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MSUWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSUWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSUWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public int Sub(int x, int y) {
            return base.Channel.Sub(x, y);
        }
        
        public int Mul(int x, int y) {
            return base.Channel.Mul(x, y);
        }
        
        public int GetSessionValue() {
            return base.Channel.GetSessionValue();
        }
        
        public void SetSessionValue(int value) {
            base.Channel.SetSessionValue(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS_lab_10_Web.MSUWS.GetHistoryResponse PIS_lab_10_Web.MSUWS.MSUWSSoap.GetHistory(PIS_lab_10_Web.MSUWS.GetHistoryRequest request) {
            return base.Channel.GetHistory(request);
        }
        
        public string GetHistory() {
            PIS_lab_10_Web.MSUWS.GetHistoryRequest inValue = new PIS_lab_10_Web.MSUWS.GetHistoryRequest();
            inValue.Body = new PIS_lab_10_Web.MSUWS.GetHistoryRequestBody();
            PIS_lab_10_Web.MSUWS.GetHistoryResponse retVal = ((PIS_lab_10_Web.MSUWS.MSUWSSoap)(this)).GetHistory(inValue);
            return retVal.Body.GetHistoryResult;
        }
    }
}
